# Generated by Django 3.1.5 on 2021-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='horario_func',
            field=models.TextField(),
        ),
    ]
